# Generated by Django 2.0.5 on 2018-05-30 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=16)),
                ('ptype', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('pdesc', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matchlist',
            fields=[
                ('pid', models.OneToOneField(on_delete=True, primary_key=True, related_name='jungo_matchlist_pid', serialize=False, to='jungo.Product')),
                ('bid', models.ManyToManyField(related_name='jungo_matchlist_bid', to=settings.AUTH_USER_MODEL)),
                ('sid', models.ManyToManyField(related_name='jungo_matchlist_sid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Selllist',
            fields=[
                ('pid', models.OneToOneField(on_delete=True, primary_key=True, related_name='jungo_selllist_pid', serialize=False, to='jungo.Product')),
                ('sid', models.ManyToManyField(related_name='jungo_selllist_sid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('pid', models.OneToOneField(on_delete=True, primary_key=True, related_name='jungo_wishlist_pid', serialize=False, to='jungo.Product')),
                ('bid', models.ManyToManyField(related_name='jungo_wishlist_bid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
