# Generated by Django 2.0.5 on 2018-06-06 06:15

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchinfo',
            fields=[
                ('buyername', models.CharField(max_length=150, unique=True)),
                ('sellername', models.CharField(max_length=150, unique=True)),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'jungo_matchinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sellinfo',
            fields=[
                ('username', models.CharField(max_length=150, unique=True)),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('prodType', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'jungo_sellinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'jungo_userinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishinfo',
            fields=[
                ('username', models.CharField(max_length=150, unique=True)),
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('prodType', models.CharField(default='A', max_length=1)),
            ],
            options={
                'db_table': 'jungo_wishinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=16)),
                ('prodType', models.CharField(choices=[('A', 'Appliances'), ('B', 'Textbooks'), ('C', 'Vehicles'), ('D', 'Others')], default='A', max_length=1)),
                ('price', models.IntegerField()),
                ('pdesc', models.TextField()),
                ('pstate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Matchlist',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jungo.Product')),
                ('buyer', models.ManyToManyField(related_name='matchlists_buyer', to='jungo.Student')),
                ('seller', models.ManyToManyField(related_name='matchlists_seller', to='jungo.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Selllist',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jungo.Product')),
                ('seller', models.ManyToManyField(related_name='selllists', to='jungo.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='jungo.Product')),
                ('buyer', models.ManyToManyField(related_name='wishlists', to='jungo.Student')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
