# Generated by Django 2.0.5 on 2018-05-31 07:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=16)),
                ('ptype', models.CharField(max_length=1)),
                ('price', models.IntegerField()),
                ('pdesc', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=12)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Matchlist',
            fields=[
                ('product', models.OneToOneField(on_delete=True, primary_key=True, related_name='matchlists', serialize=False, to='jungo.Product')),
                ('buyer', models.ManyToManyField(related_name='matchlists_buyer', to='jungo.Student')),
                ('seller', models.ManyToManyField(related_name='matchlists_seller', to='jungo.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Selllist',
            fields=[
                ('product', models.OneToOneField(on_delete=True, primary_key=True, related_name='selllists', serialize=False, to='jungo.Product')),
                ('seller', models.ManyToManyField(related_name='selllists', to='jungo.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('product', models.OneToOneField(on_delete=True, primary_key=True, serialize=False, to='jungo.Product')),
                ('buyer', models.ManyToManyField(related_name='wishlists', to='jungo.Student')),
            ],
        ),
    ]
