# Generated by Django 2.0.5 on 2018-06-05 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jungo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='matchinfo',
            table='jungo_matchinfo',
        ),
    ]
