from django.db import models
from django.contrib.auth.models import User

'''
An user who trades products.
'''
class Student(User):
    student_id = models.IntegerField(primary_key=True)      # student id.
    phone_no = models.CharField(max_length=12)              # phone number.
    balance = models.IntegerField(default=0)                # current balance.


'''
A product for trade.
Generated by user, then put into the wishlist or the selllist.
'''
class Product(models.Model):
    pid = models.IntegerField(primary_key=True)             # product id.
    pname = models.CharField(max_length=16)                 # product name.
    ptype = models.CharField(max_length=1)                  # product type.
    price = models.IntegerField()                           # price of the product.
    pdesc = models.CharField(max_length=5000, null=True)    # description of the product.


'''
A wishlist for trade.
User who wishes to buy a product put it into the wishlist.
If someone wants to sell the product, it goes to the matchlist.
'''    
class Wishlist(models.Model):
    buyer = models.ManyToManyField(Student, related_name='wishlists')           # buyer of the product.
    product = models.OneToOneField(Product, primary_key=True, on_delete=True)   # the product.


'''
A selllist for trade.
User who wishes to sell a product put it into the selllist.
If someone wants to buy the product, it goes to the matchlist.
'''    
class Selllist(models.Model):
    seller = models.ManyToManyField(Student, related_name='selllists')          # seller of the product.
    product = models.OneToOneField(Product, primary_key=True,
                                   on_delete=True, related_name='selllists')    # the product.
    

'''
A matchlist for trade.
If someone decided to trade a product in the wishlist or in the sellist,
the product and both buyer and seller put into the matchlist.
When the trade have been finished, the information is going to be deleted.
'''
class Matchlist(models.Model):
    buyer = models.ManyToManyField(Student, related_name='matchlists_buyer')    # buyer of the product.
    seller = models.ManyToManyField(Student, related_name='matchlists_seller')  # seller of the product.
    product = models.OneToOneField(Product, primary_key=True, on_delete=True,
                                   related_name='matchlists')                   # the product.
    
